services:
  php:
    build: .
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet
  nginx:
    image: nginx:1.29.5-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet

  db:
    image: mysql:8.4.8
    container_name: lnu_lle_db
    restart: unless-stopped
    env_file:
      - ./.env.docker
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
      - appnet

volumes:  
  mysql_data:
    name: capstone_i_mysql_data

networks:
  appnet:
